[project]
name = "petproject"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.128.4",
    "requests>=2.32.5",
    "uvicorn[standard]>=0.40.0",
]
